version: '3.8'

#virtual network for client jump to identity-service by domain name
networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  auction-service:
    image: arandomname/auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;User Id=postgres;Password=postgrespw;Database=auction
      - IdentityServiceUrl=http://identity-service
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - "7001:80"
      - "7777:7777"
    networks:
      custom:
  search-service:
    image: arandomname/searchservice
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    depends_on:
      - mongodb
      - auction-service
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
      - AuctionServiceUrl=http://auction-service
    ports:
      - "7002:80"
    networks:
      custom:
  identity-service:
    image: arandomname/identityservice
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ClientApp=http://app.carsties.com
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;User Id=postgres;Password=postgrespw;Database=identity
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=id.carsties.com
    networks:
      custom:
        ipv4_address: 10.5.0.200
  bid-service:
    image: arandomname/bidservice
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-service
      - GrpcAuction=http://auction-service:7777
    ports:
      - "7003:80"
    networks:
      custom:
  notify-service:
    image: arandomname/notifyservice
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - "7004:80"
    depends_on:
      - rabbitmq
    networks:
      custom:
  gateway-service:
    image: arandomname/gatewayservice
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ClientApp=https://app.carsties.com
      - VIRTUAL_HOST=api.carsties.com
    networks:
      custom:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      custom:
  mongodb:
    container_name: mongo_container
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      custom:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      custom:
  client:
    image: arandomname/client
    build:
      context: .
      dockerfile: frontend/client/Dockerfile
    volumes:
      - /var/lib/web/data
    extra_hosts:
      - id.carsties.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=I3DfhyrhvBT1o7bbaK1gCVgOMngHoUdjPfD3Qy99WXZnmKESBo
      - NEXTAUTH_URL=http://app.carsties.com
      - NEXTAUTH_URL_INTERNAL=http://client:3000
      - API_URL=http://gateway-service/
      - IDENTITY_SERVER_URL=http://id.carsties.com
      - NEXT_PUBLIC_NOTIFY_URL=https://gateway-service/notifications
      - VIRTUAL_HOST=app.carsties.com
      - Virtual_PORT=3000
    networks:
      custom:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      custom:
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
volumes:
  pgdata:
  mongodata:
