apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientapp
spec:
  selector:
    matchLabels:
      app: clientapp
  template:
    metadata:
      labels:
        app: clientapp
    spec:
      containers:
      - name: clientapp
        image: arandomname/client-app
        imagePullPolicy: Always
        env:
          - name: NEXTAUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: clientapp-secret
                key: authSecret
          - name: CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: clientapp-secret
                key: clientSecret
          - name: NEXTAUTH_URL
            value: https://app.auctionservice.store
          - name: API_URL
            value: http://gateway-clusterip/
          - name: ID_URL
            value: https://id.auction.frankfei.me
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: clientapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: clientapp
  ports:
  - port: 3000
    targetPort: 3000

