import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {Navbar} from "@/app/nav/Navbar";
import {ToasterProvider} from "@providers/ToasterProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Carsties',
    description: 'Generated by create next app',
}

export default function RootLayout({children,}: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToasterProvider />
                <Navbar/>
                <main className={"container mx-auto px-5 pt-10"}>
                    {children}
                </main>
            </body>
        </html>
    )
}
